defmodule FluxVale.Repo.Migrations.AddAuthCodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:auth_codes, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :email, :citext, null: false
      add :code_hash, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :attempts, :bigint, null: false, default: 0
    end

    create index(:auth_codes, [:email, :expires_at])
  end

  def down do
    drop_if_exists index(:auth_codes, [:email, :expires_at])

    drop table(:auth_codes)
  end
end
