defmodule FluxVale.Repo.Migrations.AddAppVersionHealthcheckPath do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:app_versions) do
      add :healthcheck_path, :text, null: false, default: "/"
    end
  end

  def down do
    alter table(:app_versions) do
      remove :healthcheck_path
    end
  end
end
