defmodule FluxVale.Repo.Migrations.AddInstancesAndAppVersionUrlEnv do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:app_versions) do
      add :instance_url_env, :text
    end

    create table(:instances, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :namespace, :text
      add :image, :text
      add :port, :bigint
      add :healthcheck_path, :text
      add :status, :text, null: false, default: "pending"
      add :status_message, :text
      add :deployed_at, :utc_datetime_usec
      add :running_since, :utc_datetime_usec
      add :storage_metering_since, :utc_datetime_usec
      add :cpu_cores, :decimal, null: false, default: "0.5"
      add :memory_mb, :bigint, null: false, default: 256
      add :storage_gb, :bigint, null: false, default: 0
      add :env_vars, :map, null: false, default: %{}

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "instances_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :cluster_id,
          references(:clusters,
            column: :id,
            name: "instances_cluster_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:instances, [:slug, :cluster_id],
             name: "instances_unique_slug_per_cluster_index"
           )

    alter table(:instances) do
      add :app_version_id,
          references(:app_versions,
            column: :id,
            name: "instances_app_version_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:instances, "instances_app_version_id_fkey")

    drop constraint(:instances, "instances_cluster_id_fkey")

    drop constraint(:instances, "instances_user_id_fkey")

    alter table(:instances) do
      remove :app_version_id
    end

    drop_if_exists unique_index(:instances, [:slug, :cluster_id],
                     name: "instances_unique_slug_per_cluster_index"
                   )

    drop table(:instances)

    alter table(:app_versions) do
      remove :instance_url_env
    end
  end
end
