defmodule FluxVale.Repo.Migrations.AddCatalogResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:app_versions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :text, null: false
      add :image, :text, null: false
      add :port, :bigint, null: false
      add :default_env_vars, :map, null: false, default: %{}
      add :configurable_env_vars, :map, null: false, default: %{}
      add :default_cpu_cores, :decimal, null: false, default: "0.5"
      add :default_memory_mb, :bigint, null: false, default: 256
      add :default_storage_gb, :bigint, null: false, default: 0
      add :release_notes, :text
      add :published_at, :utc_datetime_usec
      add :app_id, :uuid, null: false
    end

    create unique_index(:app_versions, [:version, :app_id],
             name: "app_versions_unique_version_per_app_index"
           )

    create table(:apps, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:app_versions) do
      modify :app_id,
             references(:apps,
               column: :id,
               name: "app_versions_app_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:apps) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :slug, :text, null: false
      add :tagline, :text
      add :description, :text
      add :icon_url, :text
      add :source_url, :text
      add :docs_url, :text
      add :category_id, :uuid, null: false
    end

    create unique_index(:apps, [:name], name: "apps_unique_name_index")

    create unique_index(:apps, [:slug], name: "apps_unique_slug_index")

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:apps) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "apps_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:categories) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :icon, :text
    end

    create unique_index(:categories, [:name], name: "categories_unique_name_index")

    create unique_index(:categories, [:slug], name: "categories_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    drop_if_exists unique_index(:categories, [:name], name: "categories_unique_name_index")

    alter table(:categories) do
      remove :icon
      remove :description
      remove :slug
      remove :name
      remove :updated_at
      remove :created_at
    end

    drop constraint(:apps, "apps_category_id_fkey")

    alter table(:apps) do
      modify :category_id, :uuid
    end

    drop table(:categories)

    drop_if_exists unique_index(:apps, [:slug], name: "apps_unique_slug_index")

    drop_if_exists unique_index(:apps, [:name], name: "apps_unique_name_index")

    alter table(:apps) do
      remove :category_id
      remove :docs_url
      remove :source_url
      remove :icon_url
      remove :description
      remove :tagline
      remove :slug
      remove :name
      remove :updated_at
      remove :created_at
    end

    drop constraint(:app_versions, "app_versions_app_id_fkey")

    alter table(:app_versions) do
      modify :app_id, :uuid
    end

    drop table(:apps)

    drop_if_exists unique_index(:app_versions, [:version, :app_id],
                     name: "app_versions_unique_version_per_app_index"
                   )

    drop table(:app_versions)
  end
end
