defmodule FluxVale.Repo.Migrations.CreateFeatureFlags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:feature_flags, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :key, :text, null: false
      add :enabled, :boolean, null: false, default: false
      add :rollout_percentage, :bigint
      add :description, :text
    end

    create unique_index(:feature_flags, [:key], name: "feature_flags_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:feature_flags, [:key], name: "feature_flags_unique_key_index")

    drop table(:feature_flags)
  end
end
