defmodule FluxVale.Repo.Migrations.AddAccessRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:access_rules, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :domain, :citext
      add :email, :citext
    end

    create unique_index(:access_rules, [:domain], name: "access_rules_unique_domain_index")

    create unique_index(:access_rules, [:email], name: "access_rules_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:access_rules, [:email], name: "access_rules_unique_email_index")

    drop_if_exists unique_index(:access_rules, [:domain],
                     name: "access_rules_unique_domain_index"
                   )

    drop table(:access_rules)
  end
end
