defmodule FluxVale.Repo.Migrations.AddInfrastructureCluster do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:clusters, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :kubeconfig_ref, :text
    end

    create unique_index(:clusters, [:name], name: "clusters_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:clusters, [:name], name: "clusters_unique_name_index")

    drop table(:clusters)
  end
end
